@ObservedV2
export class TransitionMap {
  static readonly FeatureMineFansSearch: string = "FeatureMineFansSearch";
  static readonly MessagePageSearch: string = "MessagePageSearch";
  static readonly PostPageMarkDown: string = "PostPageMarkDown";
  static readonly TiePageSubCategory: string = "TiePageSubCategory";
  static readonly TieDetailPageTitle: string = "TieDetailPageTitle";
  static readonly TieDetailComment: string = "TieDetailComment";
  static readonly CollectionDetailPage: string = "CollectionDetailPage";
  static CollectionContentPage: string;
}